### ISSUE TITLE
Istructions/Docs not well explained

### ISSUE THREAD

**Issue by unfairDude** [rly0nheart/oxdork#2]
10minutes stuck here with my dork.txt file

Can you add option to search urls using .txt files containing urls

**Comment by unfairDude** [comment]
> you mean searching dorks from a file?
> 
> ## Edit
> @unfairDude So I will add a feature that will allow you to use queries from a text file, or just a string as query.  The program will detect what kind of input you pass as query, between file or string.
> 
> ## Example
> Run it with queries from a file
> ```
> oxdork queries.txt
> ```
> 
> Run it with a string query
> ```
> oxdork query_string
> ```
> 
> Thanks for the suggestion! :)


yes exactly, queries inside a .txt file would be amazing.

**Comment by rly0nheart** [comment]
@unfairDude I have pushed a release to pypi. If you're still running v3.0.0, update to the latest release and you should be able to pass a file containing queries to the program.

Enjoy!

**Comment by unfairDude** [comment]
> @unfairDude I have pushed a release to pypi. If you're still running v3.0.0, update to the latest release and you should be able to pass a file containing queries to the program.
> 
> Enjoy!

just updsted it.
amazing.

I only have one issue but probably more related to google, 
When i use tor, i get the error "429 too many requests"

**Comment by rly0nheart** [comment]
> 



> > @unfairDude I have pushed a release to pypi. If you're still running v3.0.0, update to the latest release and you should be able to pass a file containing queries to the program.
> > Enjoy!
> 
> just updsted it. amazing.
> 
> I only have one issue but probably more related to google, When i use tor, i get the error "429 too many requests"

Oh yeah, that happens even when you use a VPN.
Solution is probably not using any form of VPN or Tor😅

**Comment by unfairDude** [comment]
but then you will get timeoutted if when using normal ip after 50/60 results

**Comment by rly0nheart** [comment]
> but then you will get timeoutted if when using normal ip after 50/60 results

Here's a wild idea, buy a new pc everytime you get 50 results. It's guaranteed to work😂

But serious talk, try using google cloud or gitpod

**Comment by unfairDude** [comment]
thank you, on my way to the shop 😬

**Comment by rly0nheart** [comment]
> thank you, on my way to the shop 😬

Haha good luck mate
